modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${license}"
issueTrackerURL = "${issues}"

[[mods]]
    modId = "${mod_id}"
    version = "${version}"
    displayName = "${mod_name}"
    displayURL = "${curseforge}"
    logoFile = "${mod_id}.png"
    credits = ""
    authors = "${mod_author}"
    description = '''${description}'''
    updateJSONURL = "${update_lookup}"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    versionRange = "[${forge_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "fragmentum"
    mandatory = true
    versionRange = "[${fragmentum_version},)"
    ordering = "NONE"
    side = "BOTH"
